[general]
live_config_reload = true
ipc_socket = true

[window]
title = "Alacritty"
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

dimensions = { columns = 0, lines = 0 }
padding = { x = 0, y = 0 }
position = { x = 0, y = 0 }

[terminal]
shell.program = "/usr/bin/zsh"

[font]
size = 12.0
builtin_box_drawing = true
normal = { family = "SauceCodeProNerdFontMono", style = "Regular" }
bold = { family = "SauceCodeProNerdFontMono", style = "Bold" }
italic = { family = "SauceCodeProNerdFontMono", style = "Italic" }
bold_italic = { family = "SauceCodeProNerdFontMono", style = "BoldItalic" }

[scrolling]
history = 10000
multiplier = 4

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
cursor = { cursor = "CellForeground", text = "CellBackground" }

primary = { background = "#282828", foreground = "#ebdbb2" }

# Normal colors
[colors.normal]
black = '#282828'
red = '#cc241d'
green = '#98971a'
yellow = '#d79921'
blue = '#458588'
magenta = '#b16286'
cyan = '#689d6a'
white = '#a89984'

# Bright colors
[colors.bright]
black = '#928374'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#8ec07c'
white = '#ebdbb2'


[colors.footer_bar]
background = "#c5c8c6"
foreground = "#1d1f21"

[colors.hints.end]
background = "#1d1f21"
foreground = "#e9ff5e"

[colors.hints.start]
background = "#e9ff5e"
foreground = "#1d1f21"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.search.focused_match]
background = "#000000"
foreground = "#ffffff"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"
