git:
  disableForcePushing: false
disableStartupPopups: true
gui:
  showFileTree: false
  nerdFontsVersion: ""
  showFileIcons: false
  commitAuthorShortLength: 2
  commitAuthorLongLength: 17
  commitHashLength: 8
  showBranchCommitHash: false
  skipDiscardChangeWarning: true
os:
  edit: 'nvim {{filename}}'
  editAtLine: 'nvim +{{line}} {{filename}}'

