return {
  {
    "williamboman/mason.nvim",
    cond = true,
    config = function()
      require("mason").setup({})
    end,
  },
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    cond = true,
    config = function()
      require("mason-tool-installer").setup({
        ensure_installed = {
          "bash-language-server",
          "beautysh",
          "black",
          "css-lsp",
          "cucumber-language-server",
          "docker-compose-language-service",
          "dockerfile-language-server",
          "emmet-ls",
          "fixjson",
          "google-java-format",
          "helm-ls",
          "html-lsp",
          "java-debug-adapter",
          "java-test",
          "jdtls",
          "json-lsp",
          "lua-language-server",
          "luacheck",
          "luaformatter",
          "mdformat",
          "flake8",
          "pylint",
          "prettier",
          "pyright",
          "rnix-lsp",
          "rust-analyzer",
          "stylua",
          "stylua",
          "taplo",
          "terraform-ls",
          "texlab",
          "tinymist",
          "typescript-language-server",
          "vim-language-server",
          "vue-language-server",
          "yaml-language-server",
          "yamlfix",
          "yamllint",
        },
        auto_update = false,
        run_on_start = true,
      })
    end,
  },
}
