vim.keymap.set({ "n" }, "ma", function()
  require("harpoon.mark").add_file()
end)
vim.keymap.set({ "n" }, "mm", function()
  require("harpoon.ui").toggle_quick_menu()
end)
vim.keymap.set({ "n" }, "m,", function()
  require("harpoon.ui").nav_next()
end)
vim.keymap.set({ "n" }, "mk", function()
  require("harpoon.ui").nav_prev()
end)
vim.keymap.set({ "n" }, "m1", function()
  require("harpoon.ui").nav_file(1)
end)
vim.keymap.set({ "n" }, "m2", function()
  require("harpoon.ui").nav_file(2)
end)
vim.keymap.set({ "n" }, "m3", function()
  require("harpoon.ui").nav_file(3)
end)
vim.keymap.set({ "n" }, "m4", function()
  require("harpoon.ui").nav_file(4)
end)
