---@type vim.lsp.Config
vim.lsp.config("harper-ls", {
  cmd = { "harper-ls", "--stdio" },
  filetypes = {
    "bash",
    "c",
    "cmake",
    "cpp",
    "cs",
    "dart",
    "gitcommit",
    "go",
    "haskell",
    "html",
    "java",
    "javascript",
    "lua",
    "markdown",
    "kotlin",
    "nix",
    "php",
    "python",
    "ruby",
    "rust",
    "sh",
    "swift",
    "toml",
    "typescript",
    "typescriptreact",
    "typst",
    "scala",
    "vim",
  },
  root_markers = { ".git" },
  workspace_required = false,
  settings = {
    ["harper-ls"] = {
      linters = {
        SpellCheck = true,
        SpelledNumbers = false,
        AnA = true,
        SentenceCapitalization = false,
        UnclosedQuotes = true,
        WrongQuotes = false,
        LongSentences = true,
        RepeatedWords = true,
        Spaces = true,
        Matcher = true,
        CorrectNumberSuffix = true,
      },
    },
  },
})

vim.lsp.enable("harper-ls")
