vim.keymap.set({ "n" }, "<space>ff", [[<cmd>Telescope find_files<CR>]])
vim.keymap.set({ "n" }, "<space>fF", [[<cmd>Telescope find_files hidden=true<CR>]])
vim.keymap.set({ "n" }, "<space>fg", [[<cmd>Telescope live_grep<CR>]])
vim.keymap.set({ "n" }, "<space>fl", [[<cmd> lua require'telescope.builtin'.grep_string({search = vim.fn.expand("<cword>")})<CR>]])
vim.keymap.set({ "n" }, "<space>fb", [[<cmd>Telescope buffers<CR>]])
vim.keymap.set({ "n" }, "<space>fh", [[<cmd>Telescope help_tags<CR>]])
vim.keymap.set({ "n" }, "<space>fs", [[<cmd>Telescope lsp_document_symbols<CR>]])
vim.keymap.set({ "n" }, "<space>fm", [[<cmd>Telescope harpoon marks<CR>]])
vim.keymap.set({ "n" }, "<space>fa", [[<cmd>Telescope man_pages<CR>]])
vim.keymap.set({ "n" }, "<space>fcc", [[<cmd>Telescope git_commits<CR>]])
