[edit]
    command = "nvim"

[diff]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Target }}"]
    exclude = ["scripts"]

[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]

encryption = "age"
[age]
    identity = "~/.agekey.txt"
    recipients = [
        "age1fj55jsq3g8pck8fhevxglzzymqnzdqm6sluvadmk6es48cayy33smmwcz4",
        "age1tduwep92y009u8dg0ewvu25ez5ajkupu840kudsy5c0v76w7m5cqqhxl9r"
    ]

[git]
    autoCommit = true
    autoPush = false # be careful with secret when this is enable
