name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, ubuntu-latest]
    runs-on: ${{matrix.os}}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: chezmoi init
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .
