name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, ubuntu-latest]
    runs-on: ${{matrix.os}}
    env:
      GITHUB_CI: true
    timeout-minutes: 10
    steps:
      - name: setup age ${{ matrix.os }}
        uses: AnimMouse/setup-age@main
      - name: setup age private key from secrets ${{ matrix.os }}
        run:  echo '${{ secrets.AGE1FJ55JSQ3G8PCK8FHEVXGLZZYMQNZDQM6SLUVADMK6ES48CAYY33SMMWCZ4 }}' > /opt/agekey.txt
      - uses: actions/checkout@v4
      - name: chezmoi init ${{ matrix.os }}
        run:  sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .
