name: gitleaks

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # every day at 4am

jobs:
  gitleaks:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
        name: checkout-${{ matrix.os }}
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        name: gitleaks-${{ matrix.os }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
